ddp:
    master_addr: "localhost"
    master_port: "0"
    num_devices: 1


rlbench:
    task_name: "multi"
    tasks:
    - bimanual_push_box
    - bimanual_lift_ball
    - bimanual_pick_plate
    - bimanual_put_item_in_drawer
    - bimanual_put_bottle_in_fridge
    - bimanual_pick_laptop
    - bimanual_sweep_to_dustpan
    - bimanual_lift_tray
    - bimanual_handover_item_easy
    - bimanual_take_tray_out_of_oven
    demos: 100
    demo_path: /root/data/train
    episode_length: 25
    cameras: ["over_shoulder_left", "over_shoulder_right", "overhead", "wrist_right", "wrist_left", "front"]
    # cameras: ["wrist", "wrist2", "front"]
    camera_resolution: [128, 128]
    scene_bounds: [-0.3, -0.5, 0.6, 0.7, 0.5, 1.6]
    include_lang_goal_in_obs: True

replay:
    batch_size: 72
    timesteps: 1
    prioritisation: False
    task_uniform: True # uniform sampling of tasks for multi-task buffers
    use_disk: True
    path: '/tmp/' # only used when use_disk is True.
    max_parallel_processes: 32

framework:
    log_freq: 100
    save_freq: 2000
    train_envs: 1
    replay_ratio: ${replay.batch_size}
    transitions_before_train: 200
    tensorboard_logging: True
    csv_logging: True
    training_iterations: 500000
    gpu: 0
    env_gpu: 0
    logdir: '/root/code/peract2/logs'
    logging_level: 20 # https://docs.python.org/3/library/logging.html#levels
    seeds: 1
    start_seed: 0
    load_existing_weights: True
    num_weights_to_keep: 60 # older checkpoints will be deleted chronologically
    num_workers: 0
    record_every_n: 5
    checkpoint_name_prefix: "checkpoint"

defaults:
    - method: RRVT

hydra:
    run:
        dir: ${framework.logdir}/${rlbench.task_name}/${method.name}
